CREATE TABLE Credentials (userID INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (userID), username VARCHAR(11) CHARACTER SET utf8 NOT NULL,
passwordHash VARCHAR(255) NOT NULL);

CREATE TABLE UserData (userID INT DEFAULT NULL, coins INT NOT NULL, gems INT NOT NULL, trophies INT NOT NULL);